name: Reuseable Workflow
on:
  workflow_call:
    inputs:
      artifact_name:
        description: Name of the artifact
        required: false
        default: dist
        type: string
    secrets:
      REUSE_SECREAT:
        required: true
    outputs:
      result:
        description: The result of the deploy job
        value: ${{ jobs.deploy.outputs.outcome }}

jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-output.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact_name}}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying and Uploading artifacts"
      - name: Set results output
        id: set-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
